### ISSUE TITLE
Parametrise ARTI computation

### ISSUE THREAD

**Issue by AJRubio-Montero** [lagoproject/onedataSim#3]
It is developing new ARTI parameters that should be included in onedataSim. Thus this task depends on: #https://github.com/lagoproject/arti/issues/2

- [x] To propagate `-x`  parameter ( enable default values) in `arguments.py`
- [x] To propagate rest of new parameters in `arti/do_sims.sh` in `arguments.py`

**Comment by rpaganmunoz** [comment]
The codes (do_sims.sh and arguments.py) have been updated for all missing parameters. Done at branch dev-rpaganmunoz. Simulations not writing data in EGI OneData
